# Generated by Django 4.2.8 on 2023-12-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
